sudo: false
cache: bundler
language: ruby
rvm:
  - 2.4.1
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.4.2.x
matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.1.5
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 1.9.3
    gemfile: Gemfile
  - rvm: 2.0.0
    gemfile: Gemfile
  - rvm: 2.1.5
    gemfile: Gemfile
